\c porsche_dev;

INSERT INTO porsches (name, image, year, color, generation, price, description, featured,  is_new, rating) VALUES
('911 Carrera', 'https://bringatrailer.com/wp-content/uploads/2022/01/2002_porsche_911-carrera_2002_porsche_911-carrera_79b5293f-6f10-44f2-9dda-11161e728943-73067-1-73091.jpeg?fit=940%2C627', 2000, 'Silver', 996, 37000, 'Near flawless example of an 996 carerra in Silver. The iconic color for any German car. Great entry into 911 ownership', false, false, 5),
('911 Targa', 'https://bringatrailer.com/wp-content/uploads/2022/01/2019_porsche_targa-4_dscf4941-40513.jpg?fit=940%2C626', 2019, 'Red', 991, 102000, 'Barely driven 911 Targa in Guards red. Low mileage. A real headturner!!!', true, false, 5),
('911 Cabriolet', 'https://bringatrailer.com/wp-content/uploads/2022/01/1997_porsche_911-carrera-cabriolet_tempImageGux34t-1.jpg?fit=940%2C627', 1998, 'White', 993, 57000, 'A stunning example of the 993, the last air cooled 911, in white with convertible top. The 993 prices are climbing, grab one now!',false, false, 3),
('911 4S Cabriolet', 'https://bringatrailer.com/wp-content/uploads/2021/12/2004_porsche_911-carrera-4s_DSC06146-1.jpg?fit=940%2C627', 2002, 'Green', 996, 44000, 'Stunning 996 generation Porsche in a timeless color. Great weekend car or even a daily driver!',false, false, 5),
('Carrera 4s', 'https://bringatrailer.com/wp-content/uploads/2021/12/2012_porsche_911-carrera-4-gts_IMG_1708-2.jpeg?fit=940%2C627', 2007, 'Black', 997, 30000, '997 Porsche in black. GREAT price! Only a few more years until the 997 is considered a classic. A truly modern Porsce 911 at a great price!', false , false, 5);

INSERT INTO generations (generation, image, beganProd, endedProd, description)
VALUES
('First generation', 'https://www.topgear.com/sites/default/files/news-listicle/image/s13_0027_fine.jpg?w=1290&h=726', 1963, 1973, 'The birth of a legend. Porsche wanted to offer a larger, four-seater version of its 356, specifically its expensive and complicated Carrera 2. The all-new car featuring a new chassis with MacPherson struts, semi-trailing arms and torsion bar springs, and a brand-new air-cooled, OHC flat-six “boxer” engine mounted in the rear of the car and coupled with either a four or five-speed manual gearbox.Assembled in Leipzig, Germany, the 911 initially made 128 horsepower from its 1,991cc engine and a top speed of 131 mph.'),
('G-model', 'https://www.topgear.com/sites/default/files/news-listicle/image/36191-f-por.jpg?w=1290&h=726', 1973, 1989,  'A decade into the 911s life and Porsche decided an update was needed and gave the 911 a big makeover. Known as the G-model 911 it sold almost 200,000 vehicles and was the longest running 911 series, being produced from 1973 to 1989. In addition to a Coupé and a Targa version, a Cabriolet was also available. There were meaningful design changes to the 911, most notably a new raised bumper design with black plastic bellows (designed to meet U.S crash test standards). Between the tail lights of the G models is a red panel and a Porsche logo that is red or black, depending on the model year. The rear number plate is flanked by two large rubber buffers with integrated number plate lighting. Inside, the G Series 911 came with added safety features to appease U.S regulators and consumers, including three-point safety belts fitted as standard and seats with integrated headrests.'),
('Nine-Six-Four', 'https://www.topgear.com/sites/default/files/news-listicle/image/s13_0018_fine.jpg?w=1290&h=726', 1989, 1994, 'The 964, to give it its internal codename, arrived at the very end of the 1980s, bringing with it some mildly updated styling but a whole heap of new tech.' ),
('Nine-Nine-Three', 'https://www.topgear.com/sites/default/files/news-listicle/image/s13_0022_fine.jpg?w=1290&h=726', 1994, 1998, 'Were going to stick with Porsches internal model codes, both to avoid confusion and because theyre reasonably well known among car nerds. The 993 arrived just five years after the 964, and is still regarded by many Porsche die-hards as the prettiest and best-judged of the lot.'),
('Nine-Nine-Six', 'https://www.topgear.com/sites/default/files/news-listicle/image/p98_0518_a4.jpg?w=1290&h=726', 1998, 2004, 'While Theos favorite 911 generation, the 996 is overal the most hated 911. Following such a loved generation of car, the 1998 arrival of the water-cooled 996 was met with grumbles and cries of "its lost its character", something of a running theme for new-generation 911s and the implacable Porsche aficionados theyve tried to please.'),
('Nine-Nine-Seven', 'https://www.topgear.com/sites/default/files/news-listicle/image/p05_0707_a4.jpg?w=1290&h=726', 2004, 2011, 'Round headlights made a swift return in 2004, with the arrival of an all-new 911 generation. Its shape was broadly the same as the 996, but its detailing more delicate. All had more than 300bhp, while a new GT2 entered unchartered territory with 530bhp.'),
('Nine-Nine-One', 'https://www.topgear.com/sites/default/files/news-listicle/image/p11_0621_a4.jpg?w=1290&h=726', 2011, 2018, 'The 991 arrived in 2011, and while it may have been coined the prettiest 911 in decades, nothing could save it from a wrath of criticism for its new electric steering. It will go down in history as the last of the 911s to have naturally aspirated Carreras that rev to the heavens…'),
('Nine-Nine-Two (Current)', 'https://www.topgear.com/sites/default/files/news-listicle/image/rp_-_992_press_drive-15.jpg?w=1290&h=726', 2018, 2022, 'See? It doesnt look the same. The basic silhouette hasnt changed but theres a big styling leap in the shape of the long light bar at the back and full track widths for all models, not just the four-wheel-drive and motorsport cars. For now, its relatively conventional, with the Carrera models carrying over the same 3-litre flat-six turbo engines, albeit with lower emissions yet more power, in typically clever Porsche fashion.');